# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

let
  base_dir = "/containers/wordpress";
  db_dir = "${base_dir}/db";
  data_dir = "${base_dir}/data";
in
{
  systemd.tmpfiles.rules = [
    "d ${db_dir} 777 palikin users -"
    "d ${data_dir} 777 palikin users -"
  ];

  # Containers
  virtualisation.oci-containers.containers."wordpress-db" = {
    image = "mysql:5.7";
    environment = {
      "MYSQL_DATABASE" = "wordpress";
      "MYSQL_PASSWORD" = "your_mysql_password";
      "MYSQL_ROOT_PASSWORD" = "your_mysql_root_password";
      "MYSQL_USER" = "wordpress";
    };
    volumes = [
      "${db_dir}:/var/lib/mysql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=wordpress_default"
    ];
  };
  systemd.services."docker-wordpress-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-wordpress_default.service"
      "docker-volume-wordpress_db_data.service"
    ];
    requires = [
      "docker-network-wordpress_default.service"
      "docker-volume-wordpress_db_data.service"
    ];
    partOf = [
      "docker-compose-wordpress-root.target"
    ];
    wantedBy = [
      "docker-compose-wordpress-root.target"
    ];
  };
  virtualisation.oci-containers.containers."wordpress-wordpress" = {
    image = "wordpress:latest";
    environment = {
      "WORDPRESS_DB_HOST" = "db:3306";
      "WORDPRESS_DB_PASSWORD" = "your_mysql_password";
      "WORDPRESS_DB_USER" = "wordpress";
    };
    volumes = [
      "${data_dir}:/var/www/html:rw"
    ];
    ports = [
      "8000:80/tcp"
    ];
    dependsOn = [
      "wordpress-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=wordpress"
      "--network=wordpress_default"
    ];
  };
  systemd.services."docker-wordpress-wordpress" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-wordpress_default.service"
      "docker-volume-wordpress_wp_data.service"
    ];
    requires = [
      "docker-network-wordpress_default.service"
      "docker-volume-wordpress_wp_data.service"
    ];
    partOf = [
      "docker-compose-wordpress-root.target"
    ];
    wantedBy = [
      "docker-compose-wordpress-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-wordpress_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f wordpress_default";
    };
    script = ''
      docker network inspect wordpress_default || docker network create wordpress_default
    '';
    partOf = [ "docker-compose-wordpress-root.target" ];
    wantedBy = [ "docker-compose-wordpress-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-wordpress_db_data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect wordpress_db_data || docker volume create wordpress_db_data
    '';
    partOf = [ "docker-compose-wordpress-root.target" ];
    wantedBy = [ "docker-compose-wordpress-root.target" ];
  };
  systemd.services."docker-volume-wordpress_wp_data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect wordpress_wp_data || docker volume create wordpress_wp_data
    '';
    partOf = [ "docker-compose-wordpress-root.target" ];
    wantedBy = [ "docker-compose-wordpress-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-wordpress-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
